### PR TITLE
Adding Belgrade as submodule

### PR DESCRIPTION
**Pull request by stalker314314**

### CODE REVIEW

**Comment by jbelien** [comment]
Awesome ! 😍 
I'll merge it right after fixing the last bits of code (scripts/map) where variables are related to Brussels !

**Comment by jbelien** [comment]
Now that I have updated the scripts, could you run it again ?
Just to be sure we have the last version of the structure before merging !

Thanks A LOT !

**Comment by jbelien** [comment]
You'll also have to add the map settings to your HTML files (see https://github.com/openknowledgebe/equalstreetnames/issues/20#issuecomment-620188135)

**Comment by stalker314314** [comment]
I checked and everything is fine. I will send PR to add custom map style, but I don't see any other problem

**Comment by jbelien** [comment]
Good idea to add the style as a setting too !
I'll make the update !

**Comment by jbelien** [comment]
Map style is now configurable for your files !

You just have to add the following to your HTML files (with the correct settings for Belgrade, of course):
```html
<script>
  app.center = [4.3651, 50.8355];
  app.zoom = 11;
  app.bbox = [4.243544, 50.763726, 4.482277, 50.913384];
  app.countries = "be";
  app.style = "mapbox://styles/mapbox/dark-v10";
  app.init();
</script>
```

(see [`en/index.html`](https://github.com/openknowledgebe/equalstreetnames-brussels/blob/master/html/en/index.html#L351-L358))

**Comment by stalker314314** [comment]
Confirming everything works

**Comment by jbelien** [comment]
Awesome !

Can you sync your PR so it's using commit https://github.com/stalker314314/equalstreetnames-belgrade/commit/46e40f3578d526d03736e26e73beaf07750b5d79 (instead of https://github.com/stalker314314/equalstreetnames-belgrade/commit/9cae3f43ac92df2cbf6d2f566b7fa619dde4440d) ?

I'll merge the PR once it's synced! 🚀 🍾

**Comment by jbelien** [comment]
Awesome ! Thank you so much for your help @stalker314314 !

**Pull request merged**
